# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
  - name: ADDON
    value: addon
trigger:
- master
pr: none

pool:
  name: 'Default'
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "${PWD}/$ADDON"
    ls -al
    docker run --rm --privileged -v ~/.docker:/root/.docker -v ${PWD}/addon:/data -v /var/run/docker.sock:/var/run/docker.sock:ro homeassistant/amd64-builder --all -t /data --docker-user $DOCKERUSER --docker-password $DOCKERPASS
  displayName: 'Build Add-on'
  env:
    DOCKERUSER: $(dockeruser)
    DOCKERPASS: $(dockerpass)